// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryFilterController from "./category_filter_controller"
application.register("category-filter", CategoryFilterController)

import GridController from "./grid_controller"
application.register("grid", GridController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
